version: '3'
services:
  db-backend:
    image: mysql
    container_name: db-backend
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    networks:
      - connect-fiverr
  backend:
    depends_on:
      - db-backend
    container_name: backend_fiverr
    env_file:
      - .env
    build: .
    ports:
      - 3000:3001
    networks:
      - connect-fiverr
networks:
  connect-fiverr:
