version: '3'
services:
  mysqlDB:
    image: mysql
    container_name: mysqlDB
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3310:3306
    networks:
      - connectFiverr
  backend:
    depends_on:
      - mysqlDB
    container_name: backend
    env_file:
      - .env
    build: .
    ports:
      - 3001:3000
    networks:
      - connectFiverr
networks:
  connectFiverr:
