version: '3'
services:
  mysqlDB:
    image: mysql
    container_name: mysqlDB
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3311:3306
    networks:
      - connectFiverr
  backend:
    depends_on:
      - mysqlDB
    container_name: backend_fiverr
    env_file:
      - .env
    build: .
    ports:
      - 3000:3001
    networks:
      - connectFiverr
networks:
  connectFiverr:
